CREATE TABLE GO_AUDITORIA
  (
    ID             NUMBER (16,2) NOT NULL ,
    TABELA         VARCHAR2 (30) NOT NULL ,
    TIPO_ALTERACAO VARCHAR2 (10) NOT NULL ,
    HISTORICO      VARCHAR2 (4000) ,
    DATA           DATE NOT NULL ,
    USUARIO        VARCHAR2 (300) NOT NULL
  ) ;

ALTER TABLE GO_AUDITORIA ADD CHECK ( TIPO_ALTERACAO IN ('DELETE', 'UPDATE')) ;
COMMENT ON COLUMN GO_AUDITORIA.ID IS  'Mensagem que o usuario esta enviando para o GOLPHERS' ;
COMMENT ON COLUMN GO_AUDITORIA.TABELA IS 'Contem o nome da tabela que recebeu a alteracao' ;
COMMENT ON COLUMN GO_AUDITORIA.TIPO_ALTERACAO IS 'Informar se foi UPDATE ou DELETE' ;
COMMENT ON COLUMN GO_AUDITORIA.HISTORICO IS 'CASO SEJA ALTERAÇÃO, INFORMAR OS CAMPOS QUE FORAM ALTERADOS' ;
COMMENT ON COLUMN GO_AUDITORIA.DATA IS 'Data que foi realizada a alteração ou exclusão' ;
COMMENT ON COLUMN GO_AUDITORIA.USUARIO IS 'LOGIN DO USUARIO QUE REALIZOU A ALTERAÇÃO' ;
ALTER TABLE GO_AUDITORIA ADD CONSTRAINT GO_AUDITORIA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE GO_CATEGORIA
  (
    ID        NUMBER (16,2) NOT NULL ,
    CATEGORIA VARCHAR2 (200) NOT NULL ,
    STA_ATIVO VARCHAR2 (1) DEFAULT 'N' NOT NULL
  ) ;

ALTER TABLE GO_CATEGORIA ADD CONSTRAINT GOCATE_STAT_CK CHECK ( STA_ATIVO IN ('N', 'S')) ;
COMMENT ON TABLE GO_CATEGORIA IS 'Tabela de Categoria' ;
COMMENT ON COLUMN GO_CATEGORIA.ID IS 'identificador da tabela de categoria' ;
COMMENT ON COLUMN GO_CATEGORIA.CATEGORIA IS 'informa a descricao da categoria' ;
COMMENT ON COLUMN GO_CATEGORIA.STA_ATIVO IS 'Mostra se a categoria e as noticias associadas a ela, serao ou nao exibidas' ;
ALTER TABLE GO_CATEGORIA ADD CONSTRAINT GO_CATEGORIA_PK PRIMARY KEY ( ID ) ;
ALTER TABLE GO_CATEGORIA ADD CONSTRAINT CATE_STA_ATIVO_UN UNIQUE ( CATEGORIA , STA_ATIVO ) ;


CREATE TABLE GO_CONTATO
  (
    ID           NUMBER (16,2) NOT NULL ,
    DT_MENSAGEM  DATE NOT NULL ,
    MENSAGEM     VARCHAR2 (2000) DEFAULT sysdate NOT NULL ,
    GO_PESSOA_ID NUMBER (16,2) NOT NULL
  ) ;

COMMENT ON COLUMN GO_CONTATO.ID IS 'identificador da tabela de contato' ;
COMMENT ON COLUMN GO_CONTATO.DT_MENSAGEM IS 'data que a mensagem foi postada - SYSDATE' ;
COMMENT ON COLUMN GO_CONTATO.MENSAGEM IS 'Mensagem que o usuario esta enviando para o GOLPHERS' ;
ALTER TABLE GO_CONTATO ADD CONSTRAINT GO_CONTATO_PK PRIMARY KEY ( ID ) ;


CREATE TABLE GO_NOTICIAS
  (
    ID      NUMBER (16,2) NOT NULL ,
    TITULO  VARCHAR2 (200) NOT NULL ,
    MATERIA VARCHAR2 (4000) NOT NULL ,
    IMAGEM BLOB ,
    DATA_MATERIA    DATE DEFAULT sysdate NOT NULL ,
    STA_ATIVO       VARCHAR2 (1) DEFAULT 'N' NOT NULL ,
    GO_CATEGORIA_ID NUMBER (16,2) NOT NULL
  ) ;

ALTER TABLE GO_NOTICIAS ADD CONSTRAINT GONOTI_STAT_CK CHECK ( STA_ATIVO IN ('N', 'S')) ;
COMMENT ON COLUMN GO_NOTICIAS.ID IS 'Identifacador tabela TR_NOTICIAS' ;
COMMENT ON COLUMN GO_NOTICIAS.TITULO IS 'Titulo da Materia' ;
COMMENT ON COLUMN GO_NOTICIAS.MATERIA IS 'Noticia';
COMMENT ON COLUMN GO_NOTICIAS.IMAGEM IS 'Imagem para ilustrar a materia' ;
COMMENT ON COLUMN GO_NOTICIAS.DATA_MATERIA IS 'Data que a materia foi publicado.' ;
COMMENT ON COLUMN GO_NOTICIAS.STA_ATIVO IS 'Informa se a materia sera exibida no portal ou nao' ;
ALTER TABLE GO_NOTICIAS ADD CONSTRAINT GO_NOTICIAS_PK PRIMARY KEY ( ID ) ;
ALTER TABLE GO_NOTICIAS ADD CONSTRAINT NOTI_STA_ATIVO_UN UNIQUE ( TITULO , STA_ATIVO ) ;


CREATE TABLE GO_PESSOA
  (
    ID              NUMBER (16,2) NOT NULL ,
    NOME_COMPLETO   VARCHAR2 (200) NOT NULL ,
    ENDERECO        VARCHAR2 (200) NOT NULL ,
    EMAIL           VARCHAR2 (200 CHAR) ,
    DATA_NASCIMENTO DATE NOT NULL ,
    USUARIO         VARCHAR2 (100 CHAR) ,
    SENHA RAW (200) ,
    STA_ADM VARCHAR2 (1) DEFAULT 'N' NOT NULL
  ) ;

ALTER TABLE GO_PESSOA ADD CONSTRAINT GOPESS_STAD_CK CHECK ( STA_ADM IN ('N', 'S')) ;
COMMENT ON TABLE GO_PESSOA IS 'Tabela para o cadastro de pessoas do sistema, tanto administrados, quanto clientes.' ;
COMMENT ON COLUMN GO_PESSOA.ID IS 'Identifacador tabela de clientes' ;
COMMENT ON COLUMN GO_PESSOA.NOME_COMPLETO IS 'Nome completo da pessoa' ;
COMMENT ON COLUMN GO_PESSOA.ENDERECO IS 'Endereço completo do cliente.' ;
COMMENT ON COLUMN GO_PESSOA.EMAIL IS 'Email Cliente' ;
COMMENT ON COLUMN GO_PESSOA.DATA_NASCIMENTO IS 'Data de Nascimento ' ;
COMMENT ON COLUMN GO_PESSOA.USUARIO IS 'Sera usado apenas para a Nac do Gustavo.' ;
COMMENT ON COLUMN GO_PESSOA.SENHA IS 'Sera usado apenas para a Nac do Gustavo.' ;
COMMENT ON COLUMN GO_PESSOA.STA_ADM IS 'Informa se o Usuario e administrador da aplicaçao ou nao, caso esta flag seja igual a S, entao tera acesso a area restrita' ;
ALTER TABLE GO_PESSOA ADD CONSTRAINT GO_PESSOA_PK PRIMARY KEY ( ID ) ;
ALTER TABLE GO_PESSOA ADD CONSTRAINT GO_PESSOA_USUARIO_UN UNIQUE ( USUARIO ) ;


ALTER TABLE GO_CONTATO ADD CONSTRAINT GO_CONTATO_GO_PESSOA_FK FOREIGN KEY ( GO_PESSOA_ID ) REFERENCES GO_PESSOA ( ID ) ;

ALTER TABLE GO_NOTICIAS ADD CONSTRAINT GO_NOTICIAS_GO_CATEGORIA_FK FOREIGN KEY ( GO_CATEGORIA_ID ) REFERENCES GO_CATEGORIA ( ID ) ;

